# Site settings
title: Otus AValieva
organization: Otus

# Build settings
markdown: kramdown

# Do not exclude doxygen files starting with an underscore
include:
  - _*.html
  - _images
  - _sources
  - _static


# The collection of documentation metadata
collections:
  - projects

# Jekyll extensions
gems:
  - jekyll-redirect-from
