name: otus_hw2

on:
  push:
    branches: [ "main" ]
    paths:
     - 'hm2/**'
  pull_request:
    branches: [ "main" ]
    paths: 
     - 'hm2/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
    - run: cmake ${{github.workspace}}/hm2 -DCMAKE_BUILD_TYPE="Release" -DPATCH_VERSION=${{ github.run_number }} 
    - run: cmake --build .
    - run: cmake --build . --target package
    - run: cd /home/runner/work/c_plus_otus/c_plus_otus
    - run: ./hw2
    - name: test
      id: test_result
      shell: bash
      run: |
          #bash
          res = $( md5sum sortedIps.txt  | cut -d ' ' -f 1 )"
          echo " program result is ${res}"
          test="24e7a7b2270daee89c64d3ca5fb3da1a"
          if test [ ${res} = ${test} ]; then
              echo "result equals to expected"
          else 
              echo " incorrect result !" 
          fi          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_number: Release  ${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload build
      uses: actions/upload-artifact@v4 
      with:
        name: homework2
        path: /home/runner/work/c_plus_otus/c_plus_otus
