name: otus_hw

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
    - run: sudo mkdir hm1/build
    - run: cmake -S hm1/ -B hm1/build -DCMAKE_BUILD_TYPE="Release" -DPATH_VARSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON
    - run: cd hm1/build
    - run: cmake --build .
    - run: cmake --build . --target test
    - run: cmake --build . --target package
    - name: Release
      id: cr_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_number: Release  ${{ github.run_number }}
        draft: false
        prerelease: false
