function(generate_packages NAME)
    
    set(CPACK_GENERATOR "DEB")

    set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
    set(CPACK_SOURCE_PACKAGE_VERSION ${PROJECT_VERSION})

    set(CPACK_PACKAGE_FILE_NAME ${NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME})

    include(CPack)
endfunction()
