function(generate_packages NAME)
    
    set(CPACK_GENERATOR "TGZ")
    set(CPACK_SOURCE_GENERATOR "TGZ")

    set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
    set(CPACK_SOURCE_PACKAGE_VERSION ${PROJECT_VERSION})

    set(CPACK_PACKAGE_FILE_NAME ${NAME}-${PROJECT_VERSION}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE})

    include(CPack)
endfunction()